import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

// Import Components
import ClientLayout from './ClientLayout'

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin-ext"]
})

export const metadata: Metadata = {
  title: 'Gym Kit - Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>

        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  )
}
